params = {
  custom_param:       "test value",
  checkbox_param:     true,
  email_param:        "test value",
  password_param:     "test value",
  string_param:       "test value",
  currency_param:     "20.50",
  permalink_param:    "test value",
  text_param:         "test value",
  date_param:         "2016-10-02",
  image_param:        "test value",
  radiogroup_param:   "test value",
  time_param:         "15:30",
  datetime_param:     "2016-10-02 15:30",
  number_param:       "3.5",
  select_param:       "test value",
  wysi_param:         "test value",
  file_param:         "test value",
  money_param:        "20.50",
  integer_param:      "1",
  color_picker_param: "test value",
  tags_param:         "test value",
  view_param:         "test value"
}